### ISSUE TITLE
Compilation Errors for TestBinarySearchTree

### ISSUE THREAD

**Issue by jennyafish** [Pingry-DS/binary-tree#2]
I replaced every instance of BinarySearchTree with BST for consistency, but it's getting errors because it says assertEquals() is too ambiguous

Also in `testRemove1()` should be `getValue()` instead of `get()`.

**Comment by jorndorff** [comment]
@jproudfoot I think she's right.

**Comment by jennyafish** [comment]
I converted the ints to Integer objects, changed BinarySearchTree to BST, and fixed some other things (where it was testing add on b while checking values on a), and committed the tests so they should compile and test correctly now.
